name: Django Project CI/CD

on:
  push:
    branches:
      - "main" # زمانی که تغییراتی در شاخه main رخ می‌دهد، ورک‌فلو اجرا می‌شود.
  pull_request:
    branches:
      - "main" # زمانی که درخواست pull به شاخه main ارسال می‌شود، ورک‌فلو اجرا می‌شود.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب وابستگی‌های پروژه
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # نسخه Python مورد استفاده برای پروژه شما

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # نصب وابستگی‌ها از فایل requirements.txt

      # اجرای تست‌ها در محیط Docker
      - name: Run tests using Docker
        run: |
          docker build -t my-django-app .
          docker run --rm my-django-app python manage.py test # اجرای تست‌های پروژه

      # ساخت پروژه Django
      - name: Build Django project
        run: |
          docker run --rm -v ${{ github.workspace }}:/app my-django-app bash -c "python manage.py migrate && python manage.py collectstatic --noinput"

      # اضافه کردن یک مرحله برای ارسال خروجی‌ها
      - name: Upload build artifacts (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: django-build
          path: ./_site # مسیر فایل‌های خروجی
          
  # مرحله برای انتشار (در صورت نیاز)
  deploy:
    needs: build # نیاز به مرحله build برای اجرای این مرحله
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to production..." # اینجا دستوراتی برای استقرار پروژه به سرور یا پلتفرم مورد نظر اضافه کنید.
